### ISSUE TITLE
Publication 

### ISSUE THREAD

**Issue by mattmar** [LEEClab/LS_METRICS#8]
Hello,

I was going to use LS_METRICS for some connectivity analysis and it would be great to have a publication for reference.
I see that in the wiki you report:

Niebuhr, B. B. S.; Martello, F.; Ribeiro, J. W.; Vancine, M. H.; Muylaert, R. L.; Campos, V. E. W.; Santos, J. S.; Tonetti, V. R.; Ribeiro, M. C. Landscape Metrics (LSMetrics): a spatially explicit tool for calculating connectivity and other ecologically-scaled landscape metrics. In preparation.

Is there any news on that front? Also a preprint would make it, but I couldn't find anything!

Cheers and congrats for the software.

**Comment by bniebuhr** [comment]
Dear Matteo,

I am sorry for a so delayed answer. For some reason your query did not come to me, and I was in parental leave during that time.
The paper is still in production, I am sorry for that.

In the meanwhile, you can cite:

- The software Github repository: https://zenodo.org/record/3736444#.YbchFnzMKUl
- My thesis, where this is organized so far: Niebuhr, Bernardo B. 2021. Combining landscape and movement ecology to understand connectivity and ecological processes. PhD dissertation, State University of São Paulo, Brazil. Available [here](https://repositorio.unesp.br/handle/11449/157429).
